/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIpack;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Scanner;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author welcome
 */
public class SELECT extends javax.swing.JPanel {

    /**
     * Creates new form SELECT
     */
    public SELECT() {
        initComponents();
        Connect();
    }
Connection con;
    PreparedStatement pst;
    ResultSet rs;

    public void Connect() {
        try {
            Class.forName("org.apache.derby.jdbc.ClientDriver");
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/Officers_Record ");

            Scanner sc = new Scanner(System.in);
        } catch (ClassNotFoundException e) {
            System.out.println(e);
        } catch (java.sql.SQLException e) {
            System.out.println(e);
        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        C1 = new javax.swing.JComboBox();
        C2 = new javax.swing.JComboBox();
        B1 = new javax.swing.JButton();
        B2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "OFFICER_ID", "NAME", "GENDER", "PHONE_NUMBER", "EMAIL", "RANK"
            }
        ));
        jTable1.setOpaque(false);
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 1040, 200));

        C1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        C1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "FLYING OFFICER", "FLIGHT LIEUTENANT", "SQUADRON LEADER", "WING COMMANDER", "GROUP CAPTAIN" }));
        C1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        C1.setOpaque(false);
        C1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C1ActionPerformed(evt);
            }
        });
        add(C1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 540, 150, 39));

        C2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        C2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "M", "F" }));
        C2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        C2.setOpaque(false);
        add(C2, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 540, 139, 39));

        B1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        B1.setText("SHOW");
        B1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B1ActionPerformed(evt);
            }
        });
        add(B1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 660, 117, 37));

        B2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        B2.setText("SHOW");
        B2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        B2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B2ActionPerformed(evt);
            }
        });
        add(B2, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 650, 130, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\welcome\\Desktop\\AIRCRAFT2.jpg")); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 740));
    }// </editor-fold>//GEN-END:initComponents

    private void C1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C1ActionPerformed

    private void B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B1ActionPerformed
        // TODO add your handling code here:
         String a = (String)C1.getSelectedItem();
         try{
              Class.forName("org.apache.derby.jdbc.ClientDriver");
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/Officers_Record ");
            Statement smt = con.createStatement();
           ResultSet rs = smt.executeQuery("select * from OFFICER_RECORD where RANK = '"+a+"'");
          // rs.setString(2,a);
            while (rs.next()){
                String id = String.valueOf(rs.getInt("OFFICER_ID"));
                String name = rs.getString("NAME");
                String gender = rs.getString("GENDER");
                String phno = rs.getString("PHONE_NUMBER");
                String eadd = rs.getString("EMAIL_ADDRESS");
                String rank = rs.getString("RANK");

                String tbData[] = {id, name, gender, phno, eadd, rank};
                 DefaultTableModel tb1Model = (DefaultTableModel)jTable1.getModel();
                tb1Model.addRow(tbData);
            }
         }
            catch(Exception e){
    System.out.println(e.getMessage());
}
    
    }//GEN-LAST:event_B1ActionPerformed

    private void B2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B2ActionPerformed

        String b = (String)C2.getSelectedItem();
         try{
              Class.forName("org.apache.derby.jdbc.ClientDriver");
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/Officers_Record ");
            Statement smt = con.createStatement();
           ResultSet rs = smt.executeQuery("select * from OFFICER_RECORD where GENDER = '"+b+"'");
          // rs.setString(2,a);
            while (rs.next()){
                String id = String.valueOf(rs.getInt("OFFICER_ID"));
                String name = rs.getString("NAME");
                String gender = rs.getString("GENDER");
                String phno = rs.getString("PHONE_NUMBER");
                String eadd = rs.getString("EMAIL_ADDRESS");
                String rank = rs.getString("RANK");

                String tbData[] = {id, name, gender, phno, eadd, rank};
                 DefaultTableModel tb1Model = (DefaultTableModel)jTable1.getModel();
                tb1Model.addRow(tbData);
            }
         }
            catch(Exception e){
    System.out.println(e.getMessage());
}
    

// TODO add your handling code here:
    }//GEN-LAST:event_B2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B1;
    private javax.swing.JButton B2;
    private javax.swing.JComboBox C1;
    private javax.swing.JComboBox C2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
