/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIpack;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author welcome
 */
public class UPDATE extends javax.swing.JPanel {

    /**
     * Creates new form UPDATE
     */
    public UPDATE() {
        initComponents();
        Connect();
    }
    Connection con;
    PreparedStatement pst;
    ResultSet rs;

    public void Connect() {
        try {
            Class.forName("org.apache.derby.jdbc.ClientDriver");
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/Officers_Record ");

            Scanner sc = new Scanner(System.in);
        } catch (ClassNotFoundException e) {
            System.out.println(e);
        } catch (java.sql.SQLException e) {
            System.out.println(e);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        T1 = new javax.swing.JTextField();
        T2 = new javax.swing.JTextField();
        T3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        T4 = new javax.swing.JTextField();
        T6 = new javax.swing.JTextField();
        T5 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ID1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        T7 = new javax.swing.JTextField();
        T8 = new javax.swing.JTextField();
        T9 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        T10 = new javax.swing.JTextField();
        T11 = new javax.swing.JTextField();
        T12 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText(" ENTER OFFICER ID");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 167, 51));

        ID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        ID.setOpaque(false);
        add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(771, 124, 163, 51));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("OFFICER ID ");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 160, 43));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("NAME");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(479, 291, 160, 43));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("GENDER");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 370, 160, 43));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("PHONE NUMBER");
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 460, 160, 43));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("EMAIL");
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(479, 539, 160, 43));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("RANK");
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(479, 616, 160, 43));

        T1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        T1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        T1.setOpaque(false);
        add(T1, new org.netbeans.lib.awtextra.AbsoluteConstraints(771, 212, 163, 45));

        T2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        T2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        T2.setOpaque(false);
        add(T2, new org.netbeans.lib.awtextra.AbsoluteConstraints(771, 290, 163, 44));

        T3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        T3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        T3.setOpaque(false);
        add(T3, new org.netbeans.lib.awtextra.AbsoluteConstraints(771, 368, 163, 52));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("SEARCH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1087, 114, 112, 51));

        T4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        T4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        T4.setOpaque(false);
        add(T4, new org.netbeans.lib.awtextra.AbsoluteConstraints(771, 454, 163, 47));

        T6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        T6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        T6.setOpaque(false);
        add(T6, new org.netbeans.lib.awtextra.AbsoluteConstraints(771, 537, 163, 47));

        T5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        T5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        T5.setOpaque(false);
        add(T5, new org.netbeans.lib.awtextra.AbsoluteConstraints(771, 616, 163, 43));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText(" ENTER OFFICER ID");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 167, 51));

        ID1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ID1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        ID1.setOpaque(false);
        jPanel1.add(ID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(771, 124, 163, 51));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("OFFICER ID ");
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 160, 43));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("NAME");
        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(479, 291, 160, 43));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("GENDER");
        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 370, 160, 43));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("PHONE NUMBER");
        jLabel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 460, 160, 43));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("EMAIL");
        jLabel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(479, 539, 160, 43));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("RANK");
        jLabel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(479, 616, 160, 43));

        T7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        T7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        T7.setOpaque(false);
        jPanel1.add(T7, new org.netbeans.lib.awtextra.AbsoluteConstraints(771, 212, 163, 45));

        T8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        T8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        T8.setOpaque(false);
        jPanel1.add(T8, new org.netbeans.lib.awtextra.AbsoluteConstraints(771, 290, 163, 44));

        T9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        T9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        T9.setOpaque(false);
        jPanel1.add(T9, new org.netbeans.lib.awtextra.AbsoluteConstraints(771, 368, 163, 52));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("SEARCH");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1087, 114, 112, 51));

        T10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        T10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        T10.setOpaque(false);
        jPanel1.add(T10, new org.netbeans.lib.awtextra.AbsoluteConstraints(771, 454, 163, 47));

        T11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        T11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        T11.setOpaque(false);
        jPanel1.add(T11, new org.netbeans.lib.awtextra.AbsoluteConstraints(771, 537, 163, 47));

        T12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        T12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        T12.setOpaque(false);
        jPanel1.add(T12, new org.netbeans.lib.awtextra.AbsoluteConstraints(771, 616, 163, 43));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setText("CLEAR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 660, 103, 55));

        clear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clear.setText("UPDATE");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel1.add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 660, 103, 55));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\welcome\\Desktop\\AIRCRAFT2.jpg")); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 740));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 740));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        try {
            Class.forName("org.apache.derby.jdbc.ClientDriver");
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/Officers_Record ");
            Statement smt = con.createStatement();
            String id = ID.getText();
            ResultSet rs1 = smt.executeQuery("select * from OFFICER_RECORD where OFFICER_ID = " + id + "");

            if (rs1.next()) {

                T1.setText(rs1.getString("OFFICER_ID"));
                T2.setText(rs1.getString("NAME"));
                T3.setText(rs1.getString("GENDER"));
                T4.setText(rs1.getString("PHONE_NUMBER"));
                T5.setText(rs1.getString("EMAIL_ADDRESS"));
                T6.setText(rs1.getString("RANK"));
            } else if (rs1.next() == false) {
                JOptionPane.showMessageDialog(null, "This record does not exit.");
            } else if (id.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Enter Officer ID to search.");
            }
        } catch (ClassNotFoundException | SQLException e) {
            System.out.println(e.getMessage());
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        String idc = ID.getText();
        String id = T1.getText();
        String name = T2.getText();
        String gender = T3.getText();
        String phno = T4.getText();
        String eaddress = T5.getText();
        String rank = T6.getText();
        try{
            Class.forName("org.apache.derby.jdbc.ClientDriver");
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/Officers_Record ");
            pst = con.prepareStatement("update OFFICER_RECORD set OFFICER_ID=?,NAME=?,GENDER=?,PHONE_NUMBER=?,EMAIL_ADDRESS=?,RANK=? where OFFICER_ID=?");
            pst.setString(1, id);
            pst.setString(2, name);
            pst.setString(3, gender);
            pst.setString(4, phno);
            pst.setString(5, eaddress);
            pst.setString(6, rank);
            pst.setString(7,idc );
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Updated Sucessfully !");
        }
        catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_clearActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("org.apache.derby.jdbc.ClientDriver");
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/Officers_Record ");
            ID.setText("");
            T1.setText("");
            T2.setText("");
            T3.setText("");
            T4.setText("");
            T5.setText("");
            T6.setText("");
           
                
                    }
        
        catch(ClassNotFoundException | SQLException e){
            System.out.println(e.getMessage());}
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ID;
    private javax.swing.JTextField ID1;
    private javax.swing.JTextField T1;
    private javax.swing.JTextField T10;
    private javax.swing.JTextField T11;
    private javax.swing.JTextField T12;
    private javax.swing.JTextField T2;
    private javax.swing.JTextField T3;
    private javax.swing.JTextField T4;
    private javax.swing.JTextField T5;
    private javax.swing.JTextField T6;
    private javax.swing.JTextField T7;
    private javax.swing.JTextField T8;
    private javax.swing.JTextField T9;
    private javax.swing.JButton clear;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
